### ISSUE TITLE
gg

### ISSUE THREAD

**Issue by asu01928** [Xpykerz/Spotify-Checker#2]
GG checker owner

**Comment by Xpykerz** [comment]
?

**Comment by fakartstore** [comment]
I LOVE U

**Comment by bitlayergit** [comment]
Excellent checker, worked with a 1.0M Combo... worked.

Please send me an email to dev@bitlayer.co to see if you're willing to do some checker.

**Comment by WrongProgram1** [comment]
> Excellent checker, worked with a 1.0M Combo... worked.
> 
> Please send me an email to [dev@bitlayer.co](mailto:dev@bitlayer.co) to see if you're willing to do some checker.

So it really did work?

**Comment by bitlayergit** [comment]
Worked better than some "fancy checkers around"

**Comment by Xpykerz** [comment]
enjoy
