### ISSUE TITLE
win request

### ISSUE THREAD

**Issue by cisko99za** [Xpykerz/Spotify-Checker#4]
sorry if this is not the right section but i didn't find a way (???) how to send a PM...
your link https://www.xpykerz.com/ not work and also try Pull requests section but i can't write a message...
so, my question: can you develop windows program version?
tanxs

**Comment by MQ-xz** [comment]
oh sorry about that our website is shut down due to some reasons. you can meet us at https://t.me/Xpykerz_Chat (Telegram Grp). 
and [Spotify-Checker](https://github.com/Xpykerz/Spotify-Checker/) Can run on any machine which installed Python3.

**Comment by cisko99za** [comment]
ok. tanxs for your reply! bye
