### ISSUE TITLE
work??

### ISSUE THREAD

**Issue by cisko99za** [Xpykerz/Spotify-Checker#5]
hi, sorry i have one problem,
i have python portable version 3.8.1 x64
on Console-Launcher.exe i run >>> python Spotify-Checker.py
with your Spotify-Checker.py on same folder of python portable. but i have this error:
https://i.postimg.cc/28X12bMs/ewfwf.jpg

why??

**Comment by MQ-xz** [comment]
install requirements, install pip3 first then install requests with pip3

**Comment by cisko99za** [comment]
ok. solved. installed request all work correctly. tanxs for your support! bye
