### ISSUE TITLE
another...

### ISSUE THREAD

**Issue by cisko99za** [Xpykerz/Spotify-Checker#6]
sorry for that, but i have another script but the author don't reply to my issue...
please check this script for me and help me (if u have little time for this...)
when run this script i have this problem: <syntax error at line 7> 
tanxs for help!

**Comment by cisko99za** [comment]
i have try now your script but not work....
i have tested with 3 account, 2 my free account and 1 found on web.... 2 my account is valid, but your script don't find free valid account but only 3 dead account......

**Comment by MQ-xz** [comment]
sorry about that it's maybe due to our API is down, and let me check that script you shared .

**Comment by cisko99za** [comment]
API is from spotify side, right? 
if the problem is the spotify APIs, please update your script.
aron script it's not important now. i have 9 spoty checker .exe and 3 phyton script but nothing work....
you have to update the control system by spotify otherwise nothing will work....

**Comment by ghost** [comment]
Its impossible to make spotify checker work sadly ... even if he updated  the code and it worked if would only be for such a short before it will become dead again :/ it took them long enough to change security but to many people were doing it at the same time so it was hard for them not to notice .... miss the days you could load millions of combos come back and have easy accounts in mass amount

**Comment by ghost** [comment]
api is not the only issue there is multiple issues that have caused most of checker to die

**Comment by cisko99za** [comment]
mmm.... understand. 
yet someone has succeeded in the enterprise... after endless web searches i found this link that leads to a checker and tried with some of my accounts and works well. so it's not impossible....!

**Comment by ghost** [comment]
bruh you didnt seriously use an online website checker for spotify XD  BRUH!!!!!!

**Comment by cisko99za** [comment]
oh yes. and work fine. i have try with some fake account and real my account and all work correctly...

**Comment by ghost** [comment]
If thats your choice to use a site that logs EVERY details than go for it Good Sir

**Comment by ghost** [comment]
@Xpykerz  I apologize for taking over this space wasn't done on purpose !

i was just trying to help It has gone past where it should've  and i apologize went from talking about your checker (Code)  to talking about other sites and other peoples code  .

**Comment by cisko99za** [comment]
ok exclude this site. how to work your script??

**Comment by ghost** [comment]
It just needs to be rebuilt completely due to spotify massive changes to server&site&Security  .. But is not an easy challenge sadly 

But see the issue is lets say he fixes it and keeps it Public and hundreds of people use to .. Spotify will Notice the amount of traffic ( As they have before  after they started to upgrade)  so they will change security again and Script will be dead again  and so one Sir!

i need to be CLEAR i had no part in making the script credit goes to @Xpykerz He made it im just a nobody that saw an issue open and tried to help :)

**Comment by cisko99za** [comment]
i understand what you mean, and i understand your effort. even when i can help someone always with nothing in return. and i also understand that editing the script is not easy and maybe after all a job things change again... anyway i thank you at least for your attention, which many others here have not done. and to finish i still achieved my goal.
